############################################
# Cycle Exchange                           #
############################################
# Author: Perrin Ruth                      #
# Current version: Mar. 30, 2026           #
############################################

# necessary packages
import numpy as np 
import networkx as nx
# custom codes - not intended to be used by the end user
import sparseb as spb           # sparse matrix operations on the GF(2) field
import cycxtract as extract     # extraction of the relevant cycles
# base packages useful for optimization
from time import time
from collections import defaultdict
# other
import warnings




#################################################
# 1. Fundamental Cycle Basis
#      Preliminary basis representation before 
#      computing an MCB. 
#################################################
class Fundamental_Cycle_Basis:
    """
    Generate a fundamental (Kirchoff) cycle basis, a cycle basis
    generated by a spanning tree T with a single cycle for each
    edge in E(G)\\E(T). Treated as a class with two items
      .edges:    list of edges in E(G)\\E(T).
      .edge2idx: dictionary with keys as edges (u,v) in .edges and
                 values their index in .edges
    The input is assumed to be an unweighted, undirected simple graph.
    """
    def __init__(self,G):
        # perform BFS to obtain a spanning tree
        # Node status: 0 unobserved, 1 in queue, 2 left queue
        nx.set_node_attributes(G, 0, 'BFS_color')
        # datasets we want to compute
        edge_list = []            # edges outside BFS tree
        edge_idx  = 0             # corresponding idx for edge
        edge_to_idx_dict = dict() # corresponding indices keys are tuples
        
        for u0 in G.nodes():
            # already observed component
            if G.nodes[u0]['BFS_color'] != 0: continue
            # initialize root node for given component
            queue = [(u0,None)]                        # queue stores tuples (node,parent)
            G.nodes[u0]['BFS_color'] = 1
            # search queue
            while len(queue)>0:
                u,p = queue.pop(0) # current node, parent
                G.nodes[u]['BFS_color'] = 2
                for v in G[u]:
                    if v == p: continue # skip parent
                    if G.nodes[v]['BFS_color'] == 0:          # unobserved, add to queue
                        queue.append([v,u])
                        G.nodes[v]['BFS_color'] = 1
                    elif G.nodes[v]['BFS_color'] == 1:        # edge (u,v) new and not in tree, add to edge_list
                        edge_list.append((u,v))
                        edge_to_idx_dict[(u,v)] = edge_idx
                        edge_idx+=1
                    else:                                     # edge (u,v) not in tree and already added as (v,u), include (u,v) symmetrically
                        edge_to_idx_dict[(u,v)] = edge_to_idx_dict[(v,u)]

        for node in G.nodes():
            c = G.nodes[node].pop('BFS_color') # remove auxilliary coloring from G
        self.edges = edge_list
        self.edge2idx = edge_to_idx_dict




#################################################
# 2. Cycle Decomposition
#      Main class: decomposition of a graphs cycles
#################################################
class cycle_decomposition:
    """
    Decompose the relevant cycles of a graph into pi and sli
    classes. The input is assumed to be a simple unweighted,
    undirected networkx graph. The result is a cycle_decomposition 
    object whose main components are
      .pi_classes
      .sli_classes
      .families
    These are the polyhedron-interchangeability classes, short
    loop-interchangeability classes and modified Vismara cycle
    families, respectively. They are implemented as nested
    classes. See the readme file in the main Github 
      https://github.com/perrineruth/Sampling_Minimum_Cycle_Bases
    as well as the description of the related methods and 
    objects for more information.
    """
    def __init__(self, G, verbose=False, method='full', **kwargs):
        # pass additional arguments to matrix constructor for now
        ######################################## Preliminary items ########################################
        # remove non-bicomponent edges for acceleration
        G = nx.from_edgelist(set().union(*[BCC for BCC in nx.biconnected_component_edges(G) if len(BCC)>2]))
        # Set node labels to integers; allows lists which are faster than dictionaries indexing.
        node_labels = list(G)
        try: 
            labels2node = {u:idx for idx,u in enumerate(node_labels)}   # to go the other direction
        except TypeError:
            raise TypeError('Nodes in G must be hashable')              # required to make node sets/dicts
        G = nx.convert_node_labels_to_integers(G)
        
        # Number of independent cycles
        nu = G.number_of_edges()-G.number_of_nodes()+nx.number_connected_components(G) 
        
        # Fundamental cycle basis (FCB) representation.
        FCB = Fundamental_Cycle_Basis(G)
        ###################################################################################################
        
        if verbose: start = time()
        ### 1. Construct Relevant Cycle Families
        # Give control of construction of the matrix R to an outside function smaller class, 
        # to keep code in the cycle_decomposition initializer high level.
        # Node labels are given to the cycle families which are the lowest level objects used to construct cycles.
        kwargs = {'node_labels':node_labels,'labels2node':labels2node, **kwargs} 
        RelCycMat = extract.Relevant_Cycle_Matrix_Constructor(G, FCB, nu, method=method, **kwargs)
        

        ### 2. compute the minimum cycle basis (MCB) using witness vectors, 
        # see Kavitha et al. (2009)
        Wit_Mat = spb.speye(nu)                # initial set of witness vectors Si, standard unit vectors grouped into identity
        Wit_MatT = spb.speye(nu)               # transpose, because matrix-vector products are faster than vector-matrix products
        MCB = [0 for i in range(nu)]           # 0 is a placeholder here
        MCB_idxs = np.zeros(nu, dtype=int)     # row index of MCB cycles in RelCycMat
        for i in range(nu):
            # get first row with product R0 @ S_i = 1
            Cyc,idx = RelCycMat.get_dot(Wit_Mat[:,i])
            MCB[i]  = spb.sparse_GF2_vec(sorted(Cyc),len=nu) # as a sparse FCB vector
            MCB_idxs[i] = idx
            # update future witnesses to satisfy orthogonality condition (<Si,Bj>=0 for i>j)
            dot_vec = Wit_MatT @ MCB[i]
            for j in dot_vec:
                if j>i:
                    Wit_Mat[:,j] += Wit_Mat[:,i]
                    for k in Wit_Mat[:,i]: Wit_MatT[j,k]+=1

        # Now we can retrieve the matrix and relevant cycle families, since no new families (with larger cycles) need to be generated
        # For large bicomponents this can be roughly 2x faster than constructing the full set of candidate Vismara families
        R_Mat, Rel_Cyc_Fams = RelCycMat.yield_matrix()
        # remove families larger than the maximum cycle length 
        if method == 'full' and nu>0:
            max_L = max([Rel_Cyc_Fams[MCB_idxs[i]].length for i in range(nu)])
            idx = 0
            for Fam in Rel_Cyc_Fams:
                if Fam.length<=max_L:   idx+=1
                else:                   break
            Rel_Cyc_Fams = Rel_Cyc_Fams[:idx]
            R_Mat = R_Mat[:idx,:]
        
        if verbose: 
            # This first computation is the biggest (mostly computing the Vismara families)
            stop  = time()
            print(f"Initial Vismara Families & MCB:   {stop-start:5.2f}s")
            start = time()
        

        ### 3. Backtrack to invert witness matrix used to convert cycles representation from the FCB to the MCB
        for k in range(nu-1):
            # if cycle has last MCB basis cycle in its representation then its dot with last witness=1.
            # use this to get the following inversion. Section 4.3
            # update earlier witness if their dot product is affected by adding back the later witness.
            dot_vec = Wit_MatT @ MCB[nu-k-1]
            for j in dot_vec:
                if j < nu-k-1:
                    Wit_Mat[:,j] += Wit_Mat[:,nu-k-1]
                    for l in Wit_Mat[:,nu-k-1]: Wit_MatT[j,l]+=1
        # sort MCB and Witnesses to be in increasing length
        MCB_order = sorted(range(nu), key=lambda i: Rel_Cyc_Fams[MCB_idxs[i]].length)
        MCB_idxs  = [MCB_idxs[idx] for idx in MCB_order]
        MCB       = [MCB[idx] for idx in MCB_order]
        Wit_Mat   = Wit_Mat[:,MCB_order]                  # Converts FCB -> MCB vectors
        # Convert cycles to MCB vectors
        R_Mat = R_Mat @ Wit_Mat 

        if verbose: 
            stop = time()
            print(f"Change of basis:                  {stop-start:5.2f}s")
            start= time()
        

        ### 4. Trim cycle families to only contain relevant cycles
        # cycle families are relevant if they are the sum of shorter cycles
        Fam_lens = np.array([Fam.length for Fam in Rel_Cyc_Fams])
        max_MCB_lens = np.zeros_like(Fam_lens)
        # MCB sorted by length, longest cycle in the decomposition is simply the one with largest index
        for j in range(nu): 
            max_MCB_lens[R_Mat[j]] = Rel_Cyc_Fams[MCB_idxs[j]].length
        isRelevant = (Fam_lens==max_MCB_lens) 
        # easier to slice the relevant cycles as columns in the transpose
        RT = R_Mat.T[:,isRelevant] 
        R_Mat = RT.T
        Rel_Cyc_Fams = [Rel_Cyc_Fams[i] for i,val in enumerate(isRelevant) if val]
        # update indices for MCB cycles
        Old2New_idx = np.cumsum(isRelevant)-1
        for i,Old_idx in enumerate(MCB_idxs): MCB_idxs[i] = Old2New_idx[Old_idx]
        
        if verbose: 
            stop = time()
            print(f"Remove irrelevant cycles:         {stop-start:5.2f}s")
            start= time()
        
        ### 5. Find pi classes via breadth-first search
        # consist of connected components in the bipartite graph with R_Mat as a connectivity matrix.
        pi_classes = []            
        # spanning tree over a bipartite graph split by nodes in and outside MCB
        observed = np.zeros(R_Mat.nrows,dtype=bool)
        fam2pi   = np.zeros(R_Mat.nrows,dtype=int)
        for j in range(nu):
            # construct pi class containing jth MCB cycle
            # skip if already observed
            if observed[MCB_idxs[j]]: continue 
            # two items for each pi class, [MCB cycles, and # Families in pi class]
            pi_classes.append([[j],1])
            queue = [j]
            observed[MCB_idxs[j]] = True
            fam2pi[MCB_idxs[j]]=j
            while len(queue)>0:
                queue2 = []
                # search a column (in MCB to outside MCB, i.e., cycles C with given B in their decomposition)
                for col in queue:
                    for row in R_Mat[col].nonzero[1:]: # skip first entry, corresponding to the MCB cycle, use nonzero indexing which works better with slicing
                        if not observed[row]:
                            # cycles in column are sorted by length, stop searching column when cycles are too large
                            if Rel_Cyc_Fams[row].length > Rel_Cyc_Fams[MCB_idxs[col]].length: break 
                            observed[row]=True
                            fam2pi[row]=j
                            queue2.append(row)
                pi_classes[-1][1]+=len(queue2)
                # search a row (outside MCB to MCB, i.e., cycles B in the decomposition of given cycle C)
                queue=[]
                for row in queue2:
                    for col in RT[row]:
                        if not observed[MCB_idxs[col]]:
                            # not large enough yet
                            if Rel_Cyc_Fams[row].length != Rel_Cyc_Fams[MCB_idxs[col]].length: continue
                            observed[MCB_idxs[col]]=True
                            fam2pi[MCB_idxs[col]]=j
                            queue.append(col)
                pi_classes[-1][0].extend(queue)
                pi_classes[-1][1]+=len(queue)
        # pointer for the start of the block in R_Mat for each pi class
        # as pairs for the row and column in R_Mat
        pi_ptrs = np.vstack(( np.cumsum([0]+[pc[1] for pc in pi_classes]),
                              np.cumsum([0]+[len(pc[0]) for pc in pi_classes]) )).astype(int).T
        # sort R_Mat so that pi classes form consecutive columns
        colOrder = sum([pc[0] for pc in pi_classes],start=[])
        R_Mat = R_Mat[:,colOrder]
        
        ### 6. Sort rows and construct sli classes
        # sort rows in order by 
        #   a. pi class,
        #   b. number of non-zeros in block (so MCB cycles with one item appear first),
        #   c. lexicographically (read right-to-left of binary rows) so that cycles in pi and sli classes are consecutive rows.
        RT = R_Mat.T # transpose for row operations
        def aux_f(row):
            # concatenate a,b,c and use lexicographic sort of lists to do the above sort
            right2left = [col for col in RT[row].nonzero[::-1] \
                          if Rel_Cyc_Fams[row].length == Rel_Cyc_Fams[MCB_idxs[col]].length]
            return [fam2pi[row], len(right2left)] + right2left
        rowOrder = sorted(range(R_Mat.nrows), key = aux_f)
        RT = RT[:,rowOrder] # sort rows
        for i in range(nu): MCB_idxs[i] = rowOrder[MCB_idxs[i]]                # not really needed since they are just the first non-zero index in a column.
        Rel_Cyc_Fams = [Rel_Cyc_Fams[rowOrder[i]] for i in range(R_Mat.nrows)] # sort relevant cycle families
        
        # Collapse sli classes and break into block structure
        keep_row = np.ones(R_Mat.nrows,dtype=bool)
        aux = pi_ptrs.copy() # buffer for pi_ptrs which will replace it when the sli classes collapse to a single row each
        for pc_idx in range(len(pi_ptrs)-1): 
            row0,col0   = pi_ptrs[pc_idx]                   # first row/col of pi class
            nrows,ncols = pi_ptrs[pc_idx+1]-pi_ptrs[pc_idx] # number of rows/cols in block
            # expansion of row in matrix restricted to block of matrix corresponding to pi class
            prev_row = tuple([0]) # just the first MCB item
            for row in range(row0+1,row0+nrows):
                curr_row = tuple([col-col0 for col in RT[row] if col>=col0])
                # if two consecutive rows share the same cycles then they're in the same sli class
                if curr_row == prev_row: 
                    keep_row[row]=False
                    aux[(pc_idx+1):,0] -= 1
                prev_row=curr_row
        # update pi_ptrs
        pi_ptrs = aux
        # sli_ptrs, one per updated row in R_Mat, point to first index in list of cycle Families
        sli_ptrs = np.zeros(sum(keep_row)+1,dtype=int)
        sli_ptrs[:-1] = np.arange(R_Mat.nrows)[keep_row]
        sli_ptrs[-1]  = R_Mat.nrows
        # extract valid rows
        RT = RT[:,keep_row]
                    
        R_Mat=RT.T

        # Steps 5. and 6. are fairly quick.
        if verbose: 
            stop = time()
            print(f"Sort and build pi+sli classes:    {stop-start:5.2f}s")
            start= time()
        
        # entries to save after computation
        # underlying graph and fundamental cycle basis
        self.G   = G
        self.node_labels = node_labels
        self.labels2node = labels2node
        self.nu  = nu
        self.FCB = FCB
        # Vismara Families
        self.families = Rel_Cyc_Fams      # modified Vismara relevant cycle families
        # Associated matrix and decomposition into pi/sli classes
        self.R_Mat = R_Mat
        # short loop-interchangeability, as an object needs a set of families 
        self.sli_classes = [self.short_loop_class(self.families[sli_ptrs[i]:sli_ptrs[i+1]]) for i in range(R_Mat.nrows)]
        # polyhedron-interchangeability
        self.pi_ptrs = pi_ptrs            # pointers for each pi class (as row,col pairs) in the R matrix
        self.pi_classes = []
        for idx in range(len(pi_ptrs)-1):
            # indexes bounding sub matrix
            i0,j0 = self.pi_ptrs[idx]
            i1,j1 = self.pi_ptrs[idx+1]
            # polyhedron-interchangeable class is a group of short loop-interchangeability classes related by a matrix
            # we take transpose because row operations are more important for the pi class
            block_mat = self.R_Mat[i0:i1,j0:j1].T
            # define pi class by a collection of sli classes and a matrix
            self.pi_classes.append(self.polyhedron_class(self.sli_classes[i0:i1],block_mat))

        # make sure these last bits are still fast enough
        if verbose: 
            stop = time()
            print(f"Save cycle class:                 {stop-start:5.2f}s")
            start= time()
        
    
    ######### inner classes #########
    class short_loop_class:
        """
        A collection of cycles that differ by shorter cycles. Composed of
        a set of cycle families.
        """
        def __init__(self,families):
            self.families = families
            
        def random_cycle(self,rep='nodes'):
            """Sample cycle from sli class uniformly at random."""
            if len(self.families)==1:
                return self.families[0].random_cycle(rep=rep)
            weights = np.array([Fam.num_cycles for Fam in self.families])
            idx = np.random.choice(np.arange(len(self.families)), p=weights/sum(weights))
            return self.families[idx].random_cycle(rep=rep)
            
        def arbitrary_cycle(self,rep='nodes'):
            """Return an arbitrary cycle from the sli class."""
            return self.families[0].arbitrary_cycle(rep=rep)

        def nodes(self):
            """Union of nodes in sli class"""
            return set().union(*[Fam.nodes() for Fam in self.families])
        
        def edges(self):
            """Union of edges in sli class"""
            return set().union(*[Fam.edges() for Fam in self.families])
        
        def all_cycles(self,rep='nodes'):
            """All cycles belonging to sli class"""
            return sum([Fam.all_cycles(rep=rep) for Fam in self.families],start=[])

        def contains(self,C,rep='nodes'):
            """Returns True if cycle C belongs to the sli class."""
            return bool(sum([Fam.contains(C,rep=rep) for Fam in self.families]))

        def __contains__(self,item):
            # Wrapper so that the line "C in <sli_class>" uses the contains function.
            # Assumes cycle uses list of nodes representation.
            return self.contains(item)

        @property
        def num_cycles(self):
            """Number of cycles in sli class."""
            return sum([Fam.num_cycles for Fam in self.families])

        @property
        def length(self):
            """Length of cycles in sli class."""
            return self.families[0].length
        
        def __repr__(self):
            return f'short_loop_class(length={self.length},num_cycles={self.num_cycles})'

    @property
    def num_sli_classes(self):
        """Number of sli classes"""
        return len(self.sli_classes)


    class polyhedron_class:
        """
        A maximal set of relevant cycles that all can be exchanged for each other
        in some minimum cycle basis. Stored as a set of short loop-interchangeability
        classes related by a matrix.

        The matrix is the _transpose_ of the corresponding diagonal block in the
        main R matrix.
        """
        def __init__(self,sli_classes,matrix,**kwargs):
            # union of sli classes related by a matrix.
            self.sli_classes = sli_classes  
            # transposed block of the R matrix. Easier to work with rows to construct polyhedra.
            self.matrix = matrix 
        
        def random_sample(self,N=None,rep='nodes'):
            """
            Randomly sample a maximal set of mutually relevant cycles as a set of sli classes. N polyhedron shuffling steps are taken 
            to randomly select sli classes. The default number of steps grows quadratically with the dimension of the polyhedron
            space and linearly with respect to the ratio of the size of the largest and smallest sli classes.
                Output: a list of cycles with format given by rep.
            """
            # get number of shuffle steps
            npoly = self.dim_polyhedra
            match npoly:
                # cannot shuffle without polyhedra
                case 0: N = 0
                # single polyhedron, perfect shuffle in a single step
                case 1: N = 1
                case _:
                    # use default if not given
                    if N is None: 
                        sli_lens = [sc.num_cycles for sc in self.sli_classes]
                        N = int( np.ceil(2*npoly**2 * max(sli_lens)/min(sli_lens)) )
            # use polyhedron MCMC sampling to randomize
            for _ in range(N):
                # matrix form: [I:D], D some matrix to add degeneracy to block
                col_idx1 = np.random.randint(self.dim_polyhedra)+self.rank                          # index of cycle C1 to introduce into pi class
                polyhedron = self.matrix[:,col_idx1].nonzero + [col_idx1]                     # abstract polyhedron (up to shorter cycles)
                Weights = np.array( [1/self.sli_classes[i].num_cycles for i in polyhedron] )  # prob to remove sli class proportional to its inverse size
                col_idx2 = np.random.choice(polyhedron,p=Weights/sum(Weights))                # index of cycle C2 to be replaced by C1
                # if no change then skip
                if col_idx1 == col_idx2: continue
                # otherwise, C2 is in the working MCB (in I matrix), replace with C1
                # update representation of cycles, only needed for cycles other than C2
                update_vec = self.matrix[:,col_idx1] + [col_idx2] # the cycles scriptX used to exchange C1 for C2
                for aux in range(self.dim_polyhedra):
                    aux2 = aux+self.rank
                    if aux2!=col_idx1 and self.matrix[col_idx2,aux2]: 
                        # C2 is in the decomposition of C (which is not C1) 
                        # then we have to add script X to this cycles decomposition
                        self.matrix[:,aux2] += update_vec
                # finally swap the two cycles in our ordering
                aux = self.sli_classes[col_idx1]
                self.sli_classes[col_idx1] = self.sli_classes[col_idx2]
                self.sli_classes[col_idx2] = aux
            # now randomly sample from selected sli classes
            return [sc.random_cycle(rep=rep) for sc in self.sli_classes[:self.rank]]

        def arbitrary_sample(self,rep='nodes'):
            """
            Sample a full rank set of cycles from polyhedron-interchangeability class. The first set of
            sli classes are always ordered to be mutually relevant.
            """
            return [sc.arbitrary_cycle(rep=rep) for sc in self.sli_classes[:self.rank]]

        def nodes(self):
            """Union of nodes in polyhedron-interchangeability class"""
            return set().union(*[sc.nodes() for sc in self.sli_classes])
        
        def edges(self):
            """Union of edges in polyhedron-interchangeability class"""
            return set().union(*[sc.edges() for sc in self.sli_classes])

        def all_cycles(self,rep='nodes'):
            """all cycles belonging to polyhedron-iterchangeability class"""
            return sum([sc.all_cycles(rep=rep) for sc in self.sli_classes],start=[])

        def contains(self,C,rep='nodes'):
            """Returns True if cycle C belongs to the polyhedron-interchangeability class."""
            return bool(sum([sc.contains(C,rep=rep) for sc in self.sli_classes]))

        def __contains__(self,item):
            # Wrapper so that the line "C in <pi_Class>" uses the contains function.
            # Assumes cycle uses list of nodes representation.
            return self.contains(item)

        @property    
        def rank(self):
            """Number of cycles in pi class in a given MCB, equal to the rank of the block matrix representing the pi class"""
            return self.matrix.nrows

        @property   
        def dim_polyhedra(self):
            """dimension of the polyhedron space in the pi class, given by the nullity of the block matrix representing the pi class."""
            return self.matrix.ncols - self.matrix.nrows 

        @property
        def num_cycles(self):
            """Number of relevant cycles in polyhedron-interchangeability class (as the union of short loop-interchangeability classes)."""
            return sum([sc.num_cycles for sc in self.sli_classes])

        def num_samples(self):
            """
            Number of ways a full rank set of cycles can be sampled from the polyhedron-interchangeability class. Used 
            to compute the number of minimum cycle bases.

            WARNING: very slow, time-complexity exponential with respect to number of polyhedra
            """
            # matrix of polyhedra
            PMat0 = self.matrix.copy()
            # Initially [I_nu; X] rows in X are expansion cycles in polyhedra 
            # Columns in [X'; I_nullity] also include the cycle being expanded...
            # (X already transposed)
            PMat0 = spb.vstack2(PMat0[self.rank:], 
                                spb.speye(self.dim_polyhedra))
            # recursively trim sli classes until they are all mutually relevant.
            # This is significantly faster than joining sli classes despite being exponential time.
            # uses floats to reduce the risk of overflow errors.
            def num_samples_pi_class(r0=0,cur_prod=1.0,PMat=PMat0):
                num_samples = 0.0
                # stopping condition
                if PMat.ncols==0:
                    cur_prod *= np.prod([sc.num_cycles for sc in self.sli_classes[r0:]])
                    num_samples+=cur_prod
                    return num_samples
                # remove another cycle
                for r_idx in range(PMat.nrows):
                    for c_idx,col in enumerate(PMat):
                        if len(col.nonzero)>0 and col.nonzero[0] == r_idx:
                            # update matrix
                            for c_idx2,col2 in enumerate(PMat[c_idx+1:]):
                                if len(col2.nonzero)>0 and col2.nonzero[0] == r_idx:
                                    # no future cols have 1 at r_idx
                                    PMat[c_idx+c_idx2+1] += PMat[c_idx]
                            # move this to first column
                            PMat[c_idx] = PMat[0] 
                            PMat[0]=col
                            # set row to 0 to not interfere with future rows
                            PMat[r_idx,0]=0
                            # step inwards
                            num_samples+=num_samples_pi_class(r0+r_idx+1,cur_prod,PMat[r_idx+1:,1:])
                    # increase product including row r in MCB
                    cur_prod *= self.sli_classes[r0+r_idx].num_cycles
                return num_samples
            # start recursion
            return num_samples_pi_class()
            
        @property
        def length(self):
            """Length of cycles in polyhedron-interchangeability class."""
            return self.sli_classes[0].length

    @property
    def num_pi_classes(self):
        """Number of polyhedron-interchangeability classes"""
        return len(self.pi_classes)


    ######### methods: mostly for sampling minimium cycle bases #########
    def get_MCB(self, rep="nodes"):
        """
        Return the initial minimum cycle basis used to sort the cycle space. These are designed to be the arbitrary cycle
        for the first nu sli classes. Output as a list of cycles with the given format.
        """
        # each MCB cycle corresponds to the arbitrary cycle in the first sli class in a column
        return [self.sli_classes[self.R_Mat[i].nonzero[0]].arbitrary_cycle(rep=rep) for i in range(self.nu)]

    # good tests for random MCB:
    # . bicyclo[2,2,2]octane with extra paths, like spokes on a bike
    # . two large cycles with a hexagon joining them
    # . a large cycle with a nested bicyclo[2,2,2]octane
    # . degenerate case a (large cycle with a nested bicyclo[2,2,2]octane) where one of the cycles is not relevant
    # this degenerate case causes 99% of the bugs... grr
    def random_MCB(self,Nrand=None,rep="nodes",rep_MCB='cycles',merge_MCB=False,Nmerge=100,verbose=False,**kwargs):
        """
        Sample minimum cycle basis uniformly at random.
        Inputs:
         - Nrand:     number of randomization steps for polyhedron-interchangeability classes, either 
                      an integer or a function on polyhedron-interchangeability classes to integers.
         - rep:       representation of MCB cycles.
         - rep_MCB:   representation of MCB (list of 'cycles' or dual 'graph').
         - merge_MCB: boolean if pairs of MCB cycles should be modified to intersect on paths.
         - Nmerge:    maximum number of steps to merge the MCB as a safety mechanism. 

        Outputs:
         - rMCB (merge_MCB=False): random MCB as a list of cycles
         - Dual (merge_MCB=True):  dual graph representation of the random minimum cycle basis
        """
        # make Nrand into a function regardless
        if not callable(Nrand): Nrandf = lambda _: Nrand
        else:                   Nrandf = Nrand
        ##############################################
        # 1. build random MCB
        # Recursively call on polyhedron-interchangeability classes for cycles, change representation last
        if not merge_MCB:
            # rely on cycle families for rep if no merging is required
            if rep_MCB=='cycles':
                return sum([pc.random_sample(N=Nrandf(pc),rep=rep) for pc in self.pi_classes],start=[])
            elif rep_MCB=='graph': 
                raise NotImplementedError("Dual graph not implemented when merge_MCB=False")
            else:
                raise ValueError('rep_MCB must be set to either "cycles" for a list of cycles or '\
                                 +f'"graph" for a dual graph not "{rep_MCB}"')
        # use node representation if we need to merge cycles
        rMCB = sum([pc.random_sample(N=Nrandf(pc),rep='nodes') for pc in self.pi_classes],start=[])

        ##############################################
        # 2. compute and merge intersections 
        DualGraph,badPairs = build_dual(rMCB,**kwargs)
        numBad=len(badPairs)


        # merge the cycle pairs joined by multiple paths
        merge_step = 0
        if verbose: print(numBad,'initial merge steps')
        while len(badPairs)>0:
            # timeout check
            if merge_step>=Nmerge:
                print(f'Warning: minimum cycle basis failed to merge paths in {Nmerge} steps')
                break
            merge_step+=1
            # pop a random pair with random ordering
            pair = badPairs.pop(np.random.randint(len(badPairs)))
            np.random.shuffle(pair)
            # get cycles
            i,j = pair
            C1,C2 = rMCB[i],rMCB[j]
            if verbose: print(f'''C1,C2 init \nlength {len(C1)}: {C1}, \nlength {len(C2)}: {C2}''')
            flag,Cycs = merge_pair(C1,C2)
            # merge the cycles
            if flag==1: # main case, single replacement cycle for C1
                rMCB[i] = Cycs
                C1 = Cycs
            else:       # degenerate case, two candidates to swap for C1
                # locate which pi class holds C1
                idx = np.where(self.pi_ptrs[:,1]<=i)[0][-1] # index for pi class
                pc  = self.pi_classes[idx]
                row = i-self.pi_ptrs[idx,1]                 # row in dice class matrix corresponding to C1
                assert C1 in pc.sli_classes[row]              # sanity check -> correct sli class
                # determine which cycle C = C1',C1'' replaces C1
                for C in Cycs:
                    for col in range(pc.matrix.ncols):
                        # use if statement to (1) find which column sli class (column because block matrices are transposed) contains
                        #                     (2) and verify C1 is in the expansion of C using the block matrix
                        if C in pc.sli_classes[col] and row in pc.matrix[:,col]:
                            pc.sli_classes[row],pc.sli_classes[col] = pc.sli_classes[col],pc.sli_classes[row]
                            # update MCB cycle
                            rMCB[i] = C
                            C1 = C
                            # update matrix
                            update_vec = pc.matrix[:,col] + [row] # the cycles used to exchange C1 for C2
                            for col2 in range(pc.dim_polyhedra):
                                col2 += pc.rank
                                if col2!=col and pc.matrix[row,col2]: 
                                    pc.matrix[:,col2] += update_vec
                            break # already done, don't check second cycle
            if verbose: print(f'''Adjusted C1: \nlength {len(C1)}: {C1}''')
            # update cycle's nodes in dual graph
            if 'nodes' in DualGraph.nodes[i]: DualGraph.nodes[i]['nodes'] = C1
            
            # reset pairs and matrices for C1 to recompute
            badPairs = [aux for aux in badPairs if i not in aux] # remove bad pairs with C1 and recompute
            # new C1 is in the union of the old C1 and C2. Check the neighbors of the previous cycles to compute the new neighbors
            for k in set(DualGraph[i]).union(DualGraph[j]):
                if i==k: continue
                C2 = rMCB[k]
                paths = pair_intersect(C1,C2)
                # clear edge to reset, avoids errors when trying to reintroduce the edge
                if k in DualGraph[i]: DualGraph.remove_edge(i,k)
                if len(paths) == 1: # valid intersection
                    P = paths[0]
                    # add connection like above
                    idx_1,idx_2 = C1.index(P[0]),C2.index(P[0])
                    if len(P)>1 and ((C2.index(P[1])-C2.index(P[0])) % len(C2)) != 1:   idx_2 = C2.index(P[-1])
                    # indices and edge has an ordering corresponding to i<k
                    if i<k:     DualGraph.add_edge(i,k, length=len(P)-1, indices=(idx_1,idx_2))
                    else:       DualGraph.add_edge(k,i, length=len(P)-1, indices=(idx_2,idx_1))
                    # check valid path length for debugging
                    assert (len(P)-1)<=(min(len(C1),len(C2))//2), f'{C1} {C2} invalid path length'
                elif len(paths)>1: # invalid intersection
                    badPairs.append([i,k])
                    if k not in DualGraph[i]: DualGraph.add_edge(i,k) # cycles will change, skip edge attributes
        if verbose: print(merge_step,'actual merge steps')
            
        if rep_MCB=='cycles':
            if rep!='nodes': 
                warnings.warn("only 'nodes' representation is valid when mergeMCB is set True.")
            return rMCB
        elif rep_MCB=='graph':
            return DualGraph
        else: raise ValueError(f'rep_MCB must be set to either "cycles" for a list of cycles or "graph" for a dual graph not "{rep_MCB}"')

    def num_MCB(self):
        """
        Number of distinct minimum cycle bases. 
        
        WARNING: This algorithm can take exponential time in the presence of
        large polyhedron-interchangeability classes.
        WARNING: The number of MCBs is computed using floats due to potential
        exponential growth. This may cause inexact results due to floating
        point precision errors.
        """
        # solution is given by the product of the number of ways cycles can be sampled from each pi class
        return np.prod([pc.num_samples() for pc in self.pi_classes],dtype=float)

    @property
    def num_relevant_cycles(self):
        """Number of relevant cycles."""
        return sum([pc.num_cycles for pc in self.pi_classes])

    def relevant_cycles(self,rep='nodes'):
        """
        Return list of relevant cycles.
        Warning: this can take exponential time for general graphs.
        """
        return sum([pc.all_cycles(rep=rep) for pc in self.pi_classes],start=[])

    @property
    def num_essential_cycles(self):
        # enumerate essential cycles
        return sum([pc.num_cycles==1 for pc in self.pi_classes])

    def essential_cycles(self):
        # list essential cycles
        return [pc.arbitrary_sample()[0] for pc in self.pi_classes if pc.num_cycles==1]

    def draw_Mat(self,scale=None):
        """Plot the underlying R matrix relating the pi and sli classes"""
        if scale is None:   self.R_Mat.plot()
        else:               self.R_Mat.plot(scale=scale)





#################################################
# 3. MCB Pair Intersections
#      Process cycle pairs to obtain intersection
#      paths and candidate cycles to merge them.
#################################################
def build_dual(MCB,keep_nodes=False):
    DualGraph = nx.Graph()
    if keep_nodes: 
        DualGraph.add_nodes_from([(i,{'nodes':C,'length':len(C)}) for i,C in enumerate(MCB)])
    else:
        DualGraph.add_nodes_from([(i,{'length':len(C)}) for i,C in enumerate(MCB)])
    badPairs = [] # pairs of cycles (as indices) that need to be merged
    # build incidence matrix of nodes in cycles to reduce complexity
    node2cyc = defaultdict(list)
    for j,C2 in enumerate(MCB):
        # use a set to select neighbors (with smaller index) to avoid repeats
        neighs = set()
        for u in C2:
            neighs = neighs.union(node2cyc[u])
            node2cyc[u].append(j)
        for i in neighs:
            C1 = MCB[i]
            paths = pair_intersect(C1,C2)
            if len(paths)==1:
                P = paths[0]
                # index of first node in each cycle
                idx_1,idx_2 = C1.index(P[0]),C2.index(P[0])
                # compute orientation between cycles
                if len(P)>1 and C2[idx_2-1]==P[1]: # reverse orientation   
                    orientation = -1
                else:                                                               
                    orientation = +1
                # Add path as edge in dual graph. Edge (i,j) assumes i<j for "indices", which is true by node2cyc loop.
                DualGraph.add_edge(i,j, length=len(P)-1, indices=(idx_1,idx_2), orientation=orientation)
                assert (len(P)-1)<=(min(len(C1),len(C2))//2), 'invalid path length'
            elif len(paths)>1:
                badPairs.append([i,j])
                # add edge but skip attributes since they will be modified
                DualGraph.add_edge(i,j)
    return DualGraph, badPairs

def pair_intersect(C1,C2):
    """
    pair_intersect
    Finds the intersections of cycles C1 and C2 which are in list of node representation. Assumes the cycles belong
    to a common minimum cycle basis.
    Output:
     - paths = intersection paths as a list of lists of nodes with the orientation they appear in C1
    """
    k1 = len(C1)
    # first, check if there is any intersection
    shared_nodes = set(C1).intersection(C2)
    if not shared_nodes: 
        return []            # empty intersection
    
    # find index of node u in C1 that does not belong to C2, but the previous node does
    for C1_idx in range(k1):
        if C1[C1_idx] not in shared_nodes and C1[C1_idx-1] in shared_nodes:
            break
                
    # start constructing paths
    state = 0
    paths,dists = [],[1]
    for u in C1[C1_idx+1:]+C1[:C1_idx]: 
        if state == 0:  # not in path currently
            if u in shared_nodes:   # start of path
                Path,state = [u],1
                paths.append(Path)
            else:                   # still separated / between paths
                dists[-1]+=1
        else:
            if u in shared_nodes:   # continuing path
                Path.append(u)
            else:                   # end of path
                state = 0
                dists.append(1)
        
    # sort paths so first and last paths are furthest apart
    idx,d = 0,dists[0] # find argmax manually slightly faster w/o numpy
    for idx2,d2 in enumerate(dists[1:]):
        if d2>d: idx,d = idx2+1,d2
    # dist[i] is distance between path[i-1] and path[i] in terms of number of nodes
    paths = paths[idx:]+paths[:idx]
    return paths

# Test cases
# C1 = [0,1,2,3,4,5,6,7,8,9]; C2 = ['a',1,'c',3,4,'f','g','h']
# vary with C1,C2  C2,C1  C1[::-1],C2  C2,C1[::-1] etc.
# C1 = [0,1,2,3,4,5,6,7]; C2 = [0,'a','b',3,'c','d']
# C1,C2 -> random swap of 1,2
# C2,C1 -> pair of cycles
# C1 = [0,1,2,3,4,5]; C2 = [0,'a','b',3,'c','d']
# random pair of cycles
def merge_pair(C1,C2):
    """
    Modify the cycle C1 such that C1 and C2 intersect over a single path.
    Outputs:
     - flag:   (0) degenerate case (1) main case
     - Cycles: Cycles C1' to exchange for C1 in main case and cycles [C1',C1'']
               as candidates to exchange for C1 in degenerate case
    """
    # modifies C2 so that its intersection with C1 is a path
    k1,k2 = len(C1),len(C2)
    paths = pair_intersect(C1,C2)
    if len(paths) <= 1:
        # this should only be called to merge cycles that intersect over >1 paths
        print(C1,C2)
        return None # already a single path or no intersection paths
    else:
        # primary case
        i1,j1 = C1.index(paths[0][0]),C1.index(paths[-1][-1]) # start,end of intersection region
        # length of intersection area, including gaps:
        PLen = (j1-i1) % k1
        # get orientation of second cycle
        i2,j2 = C2.index(paths[0][0]),C2.index((paths[0]+paths[1])[1])
        if (j2-i2)%k2 < k2/2: orientation = 1  # forward index through C2
        else:                 orientation = -1 # reverse index through C2
        # special case a cycle has two paths half the length of the cycle
        if len(paths)==2 and len(paths[0])==len(paths[1])==1:
            if PLen==k2/2 and np.random.randint(2):
                # two valid orientations in C2, pick one at random
                orientation *= -1 
            # degenerate case for C1. Two candidate cycles for the exchange
            if PLen==k1/2:
                C1p,C1pp = C1.copy(),C1.copy() # C1' and C1''
                for t in range(1,PLen):
                    # one for each orientation in C1, return to function caller to determine which is valid
                    C1p[(i1+t)%k1] = C2[(i2+t*orientation)%k2]
                    C1pp[(i1-t)%k1] = C2[(i2+t*orientation)%k2]
                return 0,[C1p,C1pp]
        # main case, merge C1 over shared path
        C1p = C1.copy() # C1'
        for t in range(1,PLen): # skip endpoints by doing 1,PLen-1
            C1p[(i1+t)%k1] = C2[(i2+t*orientation)%k2]
        return 1, C1p
